### ISSUE TITLE
Implementar endpoint para visualizar data de notas

### ISSUE THREAD

**Issue by lupomontero** [Laboratoria/capitan-api#2]
El primer "dato" a incluir es una lista de alumnas donde podamos discernir la sede, el cohort, fecha de inicio y notas por sprint, donde cada sprint tiene nota en % a nivel técnico, HSE y premios.

Referencia de visualización generada con esta data:
https://projects.invisionapp.com/share/Z9AF3YZN5#/screens/218626343_El_Cap_UX_-_Class_Stats_V1-001

La data será consumida desde Google Drive (@chamodev a cargo del documento en drive)

**Comment by chamodev** [comment]
Aquí va el perfil de la coder:
![coder profile](https://cloud.githubusercontent.com/assets/25286921/25864305/8fba0782-34b4-11e7-98a3-a366ccfda07f.png)

**Comment by chamodev** [comment]
@lupomontero: el Google Sheet que alimenta este end-point únicamente tiene los totales para lo técnico y para HSE. Por lo tanto, podemos construir el primer gráfico con los 4 cuadrantes del [invision](https://projects.invisionapp.com/share/Z9AF3YZN5#/screens/218626343_El_Cap_UX_-_Class_Stats_V1-001), pero para generar la segunda mitad del perfil de la coder (con el detalle de cada una de las HSE), necesitaremos subir más información y ajustar el template del Google Sheet.

Lo comento para que no sea un problema hacer el ajuste luego. ¿Crees que será mucho problema hacer este trabajo de manera incremental?

Thks!
R

**Comment by coloradomarin** [comment]
@lupomontero en la experiencia que tenemos de la visualización del perfil de las coders que te pasó @chamodev vamos a incluir información adicional que estamos aun testeando con empresas. En la siguiente semana voy a incluir en más detalle que data baso a necesitar para poder armar esa experiencia.

**Comment by lupomontero** [comment]
@coloradomarin: chévere! Cierro este issue por ahora, ya que la primera iteración del endpoint ya está implementada. Cuando tengan los detalles más claros simplemente abre un issue nuevo con el feature request o sugerencia y así entra al backlog ;-)
